### ISSUE TITLE
SJ_annotated.csv failure

### ISSUE THREAD

**Issue by AlessandraLongo** [dieterich-lab/Baltica#27]
Hi again, 
following the previous suggestions, I re-ran the Baltica analysis, but I encountered a new error during the creation of the SJ_annotated.csv file.

Activating singularity image /home/cappelli/.baltica/singularity/8c8a3574e99286bac514a846a13eea14.simg
Processing DJU method output
Processing de novo annotation
Preparing annotation

Proceding with integration
Error in x@start[] <- S4Vectors:::numeric2integer(value) : 
  replacement has length zero
Calls: lapply ... start<- -> start<- -> start<- -> .set_IRanges_start
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
Execution halted
Full Traceback (most recent call last):
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2680, in run_wrapper
    runtime_sourcecache_path,
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk", line 230, in __rule_annotate
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 1567, in script
    executor.evaluate()
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 455, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 819, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 497, in _execute_cmd
    **kwargs,
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home '/home/cappelli/Desktop/Baltica_New_RGNEF/output' -B /home/cappelli/Desktop/Baltica_New_RGNEF,/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica,/tmp,/home/cappelli/Desktop/Alignment_RGNEF/hg37,/home/cappelli/Desktop/Baltica_New_RGNEF/mappings/,/home/cappelli/Desktop/Baltica_New_RGNEF/output /home/cappelli/.baltica/singularity/8c8a3574e99286bac514a846a13eea14.simg bash -c 'set -euo pipefail;  Rscript --vanilla /home/cappelli/Desktop/Baltica_New_RGNEF/output/.snakemake/scripts/tmp32n62jvb.annotate_SJ.R'' returned non-zero exit status 1.

[Fri Dec 20 11:31:46 2024]
Error in rule annotate:
    jobid: 2
    input: majiq/majiq_junctions.csv, leafcutter/leafcutter_junctions.csv, junctionseq/junctionseq_junctions.csv, rmats/rmats_junctions.csv, stringtie/merged/merged.combined.gtf
    output: results/SJ_annotated.csv
    log: logs/baltica_annotate.log (check log file(s) for error details)

Full Traceback (most recent call last):
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2680, in run_wrapper
    runtime_sourcecache_path,
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk", line 230, in __rule_annotate
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 1567, in script
    executor.evaluate()
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 455, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 819, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/script.py", line 497, in _execute_cmd
    **kwargs,
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home '/home/cappelli/Desktop/Baltica_New_RGNEF/output' -B /home/cappelli/Desktop/Baltica_New_RGNEF,/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica,/tmp,/home/cappelli/Desktop/Alignment_RGNEF/hg37,/home/cappelli/Desktop/Baltica_New_RGNEF/mappings/,/home/cappelli/Desktop/Baltica_New_RGNEF/output /home/cappelli/.baltica/singularity/8c8a3574e99286bac514a846a13eea14.simg bash -c 'set -euo pipefail;  Rscript --vanilla /home/cappelli/Desktop/Baltica_New_RGNEF/output/.snakemake/scripts/tmp32n62jvb.annotate_SJ.R'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2694, in run_wrapper
    ex, lineno, linemaps=linemaps, snakefile=file, show_traceback=True
snakemake.exceptions.RuleException: CalledProcessError in file /home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk, line 121:
Command ' singularity  exec --home '/home/cappelli/Desktop/Baltica_New_RGNEF/output' -B /home/cappelli/Desktop/Baltica_New_RGNEF,/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica,/tmp,/home/cappelli/Desktop/Alignment_RGNEF/hg37,/home/cappelli/Desktop/Baltica_New_RGNEF/mappings/,/home/cappelli/Desktop/Baltica_New_RGNEF/output /home/cappelli/.baltica/singularity/8c8a3574e99286bac514a846a13eea14.simg bash -c 'set -euo pipefail;  Rscript --vanilla /home/cappelli/Desktop/Baltica_New_RGNEF/output/.snakemake/scripts/tmp32n62jvb.annotate_SJ.R'' returned non-zero exit status 1.
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk", line 121, in __rule_annotate

RuleException:
CalledProcessError in file /home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk, line 121:
Command ' singularity  exec --home '/home/cappelli/Desktop/Baltica_New_RGNEF/output' -B /home/cappelli/Desktop/Baltica_New_RGNEF,/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica,/tmp,/home/cappelli/Desktop/Alignment_RGNEF/hg37,/home/cappelli/Desktop/Baltica_New_RGNEF/mappings/,/home/cappelli/Desktop/Baltica_New_RGNEF/output /home/cappelli/.baltica/singularity/8c8a3574e99286bac514a846a13eea14.simg bash -c 'set -euo pipefail;  Rscript --vanilla /home/cappelli/Desktop/Baltica_New_RGNEF/output/.snakemake/scripts/tmp32n62jvb.annotate_SJ.R'' returned non-zero exit status 1.
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/site-packages/baltica/analysis.smk", line 121, in __rule_annotate
  File "/home/cappelli/anaconda3/envs/baltica_env/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-12-20T112801.012941.snakemake.log

I have already checked all the input files, and their format is correct. I tried looking into the baltica_annotate.log file, but it is empty. Could you help me figure out how to resolve this issue? 
Thank you very much!
Alessandra

**Comment by tbrittoborges** [comment]
Hi Alessandra,

Did you run `baltica all`? Or are still running only leafcutter?
If the first is true, then can you please check if the seqnames is consistent among the tools (uses or not the chr prefix)? For each tool, baltica parses the output to csv file, like `junctionseq/junctionseq_junctions.csv` or `leafcutter/leafcutter_junctions.csv`.

**Comment by AlessandraLongo** [comment]
Yes I run baltica all and I already checked the seqnames, they all have the chr prefix. Actually only leafcutter_junctions.csv has this kind of format:
header | intron:
RGNEF-vs-CTR | chr11:20070741:20071382:clu:4360:+
In all the others jucntions.csv files i got the columns 'chr' with just chr indication. 
Is this normal?

**Comment by AlessandraLongo** [comment]
Hello, I have solved the problem. It seems that the chromosomes in the input files rmats_junctions.csv and leafcutter_junctions.csv were missing the ‘chr’ prefix, unlike the others. I modified them and ran the Baltica analysis step, which completed successfully. However, the final report does not include any JunctionSeq results, and upon checking its junctions.csv, I noticed that the strand information is missing, and it appears as ‘.’ for all rows. I found the note in 'DJU methods result integration' section and that is actually my case since I'm working on unstranded RNA-seq data, so is there a way to include JunctionSeq results in the integration step? 
Thanks in advance for your support and happy new year!

**Comment by tbrittoborges** [comment]
Junctionseq supports unstranded library, like the other methods. This works by not passing the --stranded option, which seems to be working correctly on my end. I have seen this problem with unstranded libraries. Can you please copy the first ten lines of `junctionseq/mergedOutput/withNovel.forJunctionSeq.gff.gz`, so I can confirm?

**Comment by AlessandraLongo** [comment]
Hi, here is:
```
chr1	ScalaUtils	aggregate_gene	11869	31109	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000423562+ENST00000438504+ENST00000450305+ENST00000456328+ENST00000469289+ENST00000473358+ENST00000488147+ENST00000515242+ENST00000518655+ENST00000538476+ENST00000541675; num 000; aggregateGeneStrand .; geneCt 3; tx_ct 11; tx_strands -,-,+,+,+,+,-,+,+,-,-; tx_cds_spans 0_0,0_0,0_0,0_0,0_0,0_0,0_0,0_0,0_0,0_0,0_0
chr1	ScalaUtils	exonic_part	11869	11871	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328; num 001; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	11872	11873	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242; num 002; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	11874	12009	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655; num 003; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12010	12057	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655+ENST00000450305; num 004; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12058	12178	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655; num 005; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12179	12227	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655+ENST00000450305; num 006; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12595	12612	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000518655; num 007; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12613	12697	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655+ENST00000450305; num 008; gene_set ENSG00000223972
chr1	ScalaUtils	exonic_part	12698	12721	.	.	.	gene_id ENSG00000223972+ENSG00000227232+ENSG00000243485; tx_set ENST00000456328+ENST00000515242+ENST00000518655; num 009; gene_set ENSG00000223972
```

**Comment by tbrittoborges** [comment]
Here you can see the strand column is missing, I assume it is missing for every entry because the workflow was run with the on unstranded mode. I don't have a solution for that.

**Comment by AlessandraLongo** [comment]
Okay, so I will work with the results from the other three tools. 
May I ask just one more question? I’m working with other RNA-seq data where the bam chromosome indication is without the 'chr' prefix, as in the annotation and genomic files. This shouldn’t interfere with the analysis, right?
Thank you so much for all your help.

**Comment by tbrittoborges** [comment]
> I’m working with other RNA-seq data where the bam chromosome indication is without the 'chr' prefix, as in the annotation and genomic files. This shouldn’t interfere with the analysis, right?
As long the GTF file you used as Baltica input is the same you used for read alignment, you should have no problems.

I am happy to help, sorry there is not much I can do regarding the junctionseq lack of strand info.
